# Common flags, etc. that can be used in the build
BUILD := x86_64-linux-gnu
HOST := arm-linux-gnueabihf
CROSS_PREFIX := $(HOST)-
TOOLCHAIN_BIN := /usr/bin
CROSS_CC := $(CROSS_PREFIX)gcc
CROSS_CXX := $(CROSS_PREFIX)g++
CROSS_LD := $(CROSS_PREFIX)ld
CROSS_AR := $(CROSS_PREFIX)ar
CROSS_AS := $(CROSS_PREFIX)as
CROSS_RANLIB := $(CROSS_PREFIX)ranlib
CROSS_STRIP := $(CROSS_PREFIX)strip
CROSS_PKG_CONFIG_LIBDIR := $(INSTALL)/lib/pkgconfig
CROSS_SYSROOT := /
HOST_SYSROOT := $(CROSS_SYSROOT)

CROSS_CPPFLAGS :=
CROSS_CFLAGS :=
CROSS_CXXFLAGS := $(CROSS_CFLAGS)
COMPILE_HOST_PATH := $(TOOLCHAIN_BIN):$(PATH)

CROSS_LDFLAGS := \
	-Wl,-s \
	-L$(INSTALL)/lib
